name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cart-service
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Unit Test
        run: yarn test
      - name: Prettier
        run: yarn prettier
      - name: Lint
        run: yarn lint
      - name: tag
        id: tag
        uses: tcpl/semver-tag-creator-action@1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          major-version: 1
