name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        working-directory: ./cart-service
        run: yarn
      - name: Unit Test
        working-directory: ./cart-service
        run: yarn test:unit
      - name: Prettier
        working-directory: ./cart-service
        run: yarn prettier ./src --check
      - name: Lint
        working-directory: ./cart-service
        run: yarn eslint ./src
